<div class="large-4 cell" style="text-align: center;">
    <div class="callout">
        <?php echo $red->Name . ' ' . $red->Type ?>
        </br>
        <?php echo $red->Cost . ' ' . $red->Rarity ?>
        </br>
        <?php echo $red->Description?>
        <a href="/item/change?item_id=<?php echo $red->item_id ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a>
        <a onclick="return confirm('Are you sure you want to delete <?php echo $red->Name?>');" href="/item/delete?item_id=<?php echo $red->item_id ?>"><i title="Delete" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </div>
</div>