<div class="large-4 cell" style="text-align: center;">
    <div class="callout">
        <?php echo $red->First_name . ' ' . $red->Last_name . ' ' . $red->Race ;?>
        </br>
        <?php echo $red->Age . ' years old';  ?>
        </br>
        <?php echo $red->Bussiness;  ?>
        </br>
        <textarea disabled name="" id="" cols="30" rows="10"><?php echo $red->Description ;?></textarea>
        </br>
        <a href="/shopkeeper/change?shopkeeper_id=<?php echo $red->shopkeeper_id ?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a>
        <a onclick="return confirm('Are you sure you want to delete <?php echo $red->First_name . ' ' . $red->Last_name ;?>');" href="/shopkeeper/delete?shopkeeper_id=<?php echo $red->shopkeeper_id ?>"><i title="Delete" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </div>
</div>