  <form action="/generated/generated" method="GET">
    <label for="type">Shop type</label>
  <select name="type" id="type">
    <option value="Blacksmith">Blacksmith</option>
    <option value="Merchant">Merchant</option>
    <option value="Magic">Magic Shop</option>
    <option value="Alchemist">Alchemy shop</option>
  </select>
  <label for="size">Shop size</label>
  <select name="size" id="size">
    <option value="Small">Small shop</option>
    <option value="Medium">Medium shop</option>
    <option value="Large">Large shop</option>
    <option value="Grand">Grand shop</option>
  </select>
  <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Generate"></input>
    </div>
</form>